entries = _{ SOI? ~ (user_name ~ separator ~ password ~ NEWLINE?)* ~ EOI }

user_name = @{ (!(":" | NEWLINE) ~ ANY)* }
separator = _{ ":" }
password = _{ (bcrypt_pass | sha_pass | md5_pass | unknown_pass) }

bcrypt_pass = @{ "$2" ~ ("a"|"b"|"y") ~ "$" ~ (!NEWLINE ~ ANY)* }
sha_pass = @{ "{SHA}" ~ (!NEWLINE ~ ANY)* }
md5_pass = @{ "$apr1$" ~ (!NEWLINE ~ ANY)* }
unknown_pass = @{ (!NEWLINE ~ ANY)* }