### These requests are used for manual testing purposes

GET http://localhost:8000/ HTTP/1.1

###
GET http://localhost:8000/test/123 HTTP/1.1

###

POST http://localhost:8000/test/post HTTP/1.1
content-type: application/json

{
    "name": "sample",
    "time": "Wed, 21 Oct 2015 18:27:50 GMT"
}
